WHITESPACE = _{ " " | "\t" | "\r" | "\n" }
document = _{ SOI ~ value ~ EOI }
value = _{ object | array | string | number | boolean | null }
object = { "{" ~ (pair ~ ("," ~ pair)*)? ~ "}" }
pair = { string ~ ":" ~ value }
array = { "[" ~ (value ~ ("," ~ value)*)? ~ "]" }
string = @{ "\"" ~ character* ~ "\"" }
character = _{ !("\"" | "\\" | '\u{0000}'..'\u{001f}') ~ ANY | "\\" ~ ("\"" | "\\" | "/" | "b" | "f" | "n" | "r" | "t" | "u" ~ ASCII_HEX_DIGIT{4}) }
number = @{ "-"? ~ ("0" | ASCII_NONZERO_DIGIT ~ ASCII_DIGIT*) ~ ("." ~ ASCII_DIGIT+)? ~ (("e" | "E") ~ ("+" | "-")? ~ ASCII_DIGIT+)? }
boolean = { "true" | "false" }
null = { "null" }

pointer = ${ SOI ~ ("/" ~ token)* ~ EOI }
token = @{ ("~" ~ ("0" | "1") | !("/" | "~") ~ ANY)* }
